baseurl = "http://humpty.xyz/"
languageCode = "en-au"
title = "humpty.xyz"
# Enable comments by entering your Disqus shortname
disqusShortname = "humpty"
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
# Define the number of posts per page
paginate = 10
footnotereturnlinkcontents = "↩"
theme = "hugo-icarus"


[permalinks]
    post = "/:slug"
    #post = "/:year/:month/:day/:slug"


[params]
    # Tell me who you are
    author = "Humphrey Murray"
    bio = "Nerd - Programmer - Hiker - Believer"
    location = "Tasmania, Australia"
    site_description = "A collection of thoughts, nerdy projects, and useful things."
    copyright  = "Powered by [Hugo](//gohugo.io). Theme by [PPOffice](http://github.com/ppoffice)."
    avatar = "css/images/avatar.png"

    # Format dates with Go's time formatting
    date_format = "2006-01-02"

# Create custom menu entries by defining a label and a link for
# them. Since you can also link posts, you've the option the
# place the links before or after them.
#
# E.g.: "Home" appears before all linked posts in the menu
# and "Tags" / "Categories" after them.
[[params.menu]]
    before = true
    label  = "Home"
    link   = "/"

[[params.menu]]
    before = false
    label  = "Tags"
    link   = "tags/"

[[params.menu]]
    before = false
    label  = "Categories"
    link   = "categories/"

# Enter a link for the follow button on the left
[params.profile]
    follow_button = "https://github.com/humphrey"


[social]
# Add your social network accounts to the profile section on the left
# by entering your username. The links to your account will be
# create automatically.
    github          = "humphrey"
    bitbucket       = "humphrey"
    jsfiddle        = ""
    codepen         = ""
    foursquare      = ""
    dribbble        = ""
    deviantart      = ""
    behance         = ""
    flickr          = ""
    instagram       = ""
    youtube         = ""
    vimeo           = ""
    vine            = ""
    medium          = ""
    wordpress       = ""
    tumblr          = ""
    xing            = ""
    linkedin        = ""
    slideshare      = ""
    stackoverflow   = ""
    reddit          = ""
    pinterest       = ""
    googleplus      = ""
    facebook        = "humphrey.murray"
    facebook_admin  = ""
    twitter_domain  = ""
    twitter         = "humphreymurray"

# Enable and disable widgets for the right sidebar
[params.widgets]
    recent_articles = true
    categories = true
    tags = true
    tag_cloud = true
